/* MOVIE TYPES */
export const MOVIE_REQUEST = 'MOVIE_REQUEST';
export const MOVIE_SUCCESS = 'MOVIE_SUCCESS';
export const MOVIE_DATA_RESET = 'MOVIE_DATA_RESET';
export const MOVIE_FAILURE = 'MOVIE_FAILURE';
/* MOVIE DETAIL TYPES */
export const MOVIE_DETAIL_REQUEST = 'MOVIE_DETAIL_REQUEST';
export const MOVIE_DETAIL_SUCCESS = 'MOVIE_DETAIL_SUCCESS';
export const MOVIE_DETAIL_FAILURE = 'MOVIE_DETAIL_FAILURE';